### ISSUE TITLE
java.lang.IndexOutOfBoundsException when using mkdocs2dita

### ISSUE THREAD

**Issue by AaronDaMommio** [jason-fox/fox.jason.readthedocs#2]
I'm trying to use the plugin to convert yml files to ditamaps + dita. I was able to validate that the commands I'm running work when I use the sample yml file /test/create-ditamap/mkdocs.yml, but they throw  java.lang.IndexOutOfBoundsException for all of the 'real' yml files I'm testing. I've attached one. Note that I tried omitting the 'markdown_extensions' and 'plugins' blocks from the yml, but I still get the same error. These yml files work fine for markdown conversions.  

Sample output:
     [copy] sbc_cne_troubleshooting omitted as C:\workgit\dt-toolsinstructions\out\sbc_cne_troubleshooting is up to date.
     [copy] sbc_cne_troubleshooting\images omitted as C:\workgit\dt-toolsinstructions\out\sbc_cne_troubleshooting\images is up to date.
     [copy] sbc_cne_troubleshooting\img omitted as C:\workgit\dt-toolsinstructions\out\sbc_cne_troubleshooting\img is up to date.
     [copy] sbc_cne_upgrade omitted as C:\workgit\dt-toolsinstructions\out\sbc_cne_upgrade is up to date.
     [copy] sbc_cne_upgrade\img omitted as C:\workgit\dt-toolsinstructions\out\sbc_cne_upgrade\img is up to date.
  [antcall] Exiting C:\workgit\dt-toolsinstructions\target\dita\build.xml.
Error: java.lang.

IndexOutOfBoundsException: Index: 0, Size: 0

**Comment by jason-fox** [comment]
I can't see the attached file - could you re-attach it please.

**Comment by AaronDaMommio** [comment]
Hmm, gave me an error when I tried to attach just now, so maybe I failed to notice the error on Friday when I tried to upload.
Attached is the set of yml files I'm trying to convert. I tested all of them, same error. Note that the one that ends with MOD is my attempt to strip down the file ... I kept removing things and testing, but same errror.
[yml.files.zip](https://github.com/jason-fox/fox.jason.readthedocs/files/5652961/yml.files.zip)

**Comment by jason-fox** [comment]
At first  glance this appears to be because you are using `nav:` in the `*.yml` and the JAR is currently only accepting the older `pages:` format. The simple workaround would be to change to `pages` before you convert.

Meanwhile I'll add in a `nav` test case and update the code to cover it when I can,

**Comment by AaronDaMommio** [comment]
I tested that case: I kept cutting down the yml in the mkdocs_pdf_cloud_requirementsMOD.yml file, and then I compared it to your sample mkdocs.yml and redid it with just one topic like this: 

pages:
- Home: index.md
... but the same error appears.

This makes me wonder if the issue is in the markdown somehow. It looks like this plugin not only tries to convert the YML but also the MD. Is there any way to just get the YML? 
The MD that we're using though for this simple example is pretty simple. I pasted the about.md below, with product names sanitized out:
 
```markdown
===
# Product Name Cloud Native Edition

## Introduction

Nokia Product Name Cloud Native Edition (ProdAcronym) is a cloud native microservices-based product that uses the DevOps model for product development.
This portal provides information related installation, upgrade, and troubleshooting in the following links:

1. [Nokia ProdAcronym Cloud Infrastructure Requirements](prod_acro_cloud_requirements/index.md)
1. [Nokia ProdAcronym Installation](prod_acro_installation/index.md)
1. [Nokia ProdAcronym Upgrade](prod_acro_upgrade/index.md)
1. [Nokia ProdAcronym Troubleshooting](prod_acro_troubleshooting/index.md)
===
1.
```

**Comment by jason-fox** [comment]
I've added a clause to allow `nav` elements - b8253f7 - try reinstalling from master:

```console
dita uninstall fox.jason.readthedocs
dita install https://github.com/jason-fox/fox.jason.readthedocs/archive/master.zip
```
