### ISSUE TITLE
args.readthedocs.template parameter does not use the selected template

### ISSUE THREAD

**Issue by PieterjanVandenweghe** [jason-fox/fox.jason.readthedocs#5]
# Starting point
When I point the parameter _args.readthedocs.template_ to a YML file, this YML file is not used to create the final mkdocs.yml in my transformation output. The default one is used.

![image](https://user-images.githubusercontent.com/43006931/152827541-4c867b61-b05b-4cc2-8ea6-97f82d024899.png)

# Expected behavior
The plug-in uses the YML file I indicated.

# Background information
- DITA-OT: 3.6.1
- Plug-in version: 1.4.1
- Published with OxygenXML 24.0

# Reference file
[mkdocs.zip](https://github.com/jason-fox/fox.jason.readthedocs/files/8016837/mkdocs.zip)

**Comment by jason-fox** [comment]
The issue here was that the template needed to be referenced relative to the `bin/dita` directory - it can now take full paths as well. Note that `theme` and `title` should not be included in the template (`theme` can be passed as a parameter and `title` is generated.)


```console
./dita -f readthedocs \
        -i ../.../document.ditamap  \
        --args.readthedocs.template=../../template.yml \
         --args.readthedocs.theme=material
```
